name: 🚀 Build Android APK

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 2 * * 0'  # 每周日凌晨2点自动构建

jobs:
  build:
    name: 🏗️ Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: ☕ Install Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: 🔍 Verify Java Installation
      run: |
        echo "验证 Java 安装..."
        java -version
        javac -version
        echo "JAVA_HOME from setup-java: $JAVA_HOME"
        ls -la $JAVA_HOME || echo "JAVA_HOME 路径不存在"

        # 将正确的 JAVA_HOME 保存到环境文件
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "正确的 JAVA_HOME 已保存: $JAVA_HOME"

    - name: 📦 Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          unzip \
          zip \
          libtool \
          libtool-bin \
          autotools-dev \
          automake \
          autoconf \
          pkg-config \
          libffi-dev \
          libssl-dev \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          libgdbm-dev \
          libdb-dev \
          liblzma-dev \
          uuid-dev

    - name: 🔧 Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "已安装的包："
        pip list
        echo "Buildozer 版本："
        buildozer version

    - name: 📱 Cache Android SDK
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-${{ runner.os }}-

    - name: 🏗️ Build APK
      run: |
        echo "开始构建 APK..."
        echo "当前目录内容："
        ls -la
        echo "检查 buildozer.spec 文件："
        cat buildozer.spec | head -20
        echo "设置构建环境..."
        export BUILDOZER_LOG_LEVEL=2

        # 验证 JAVA_HOME 环境变量
        echo "构建时 JAVA_HOME: $JAVA_HOME"
        echo "验证 Java 可用性:"
        java -version
        ls -la "$JAVA_HOME" || echo "JAVA_HOME 路径验证失败"

        # 设置 autotools 环境变量
        export ACLOCAL_PATH="/usr/share/aclocal:$ACLOCAL_PATH"
        export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH"
        export LIBTOOLIZE=libtoolize
        export AUTORECONF_FLAGS="-fiv"

        # 强制重新生成 autotools 缓存
        sudo rm -rf /usr/share/aclocal/libtool.m4 2>/dev/null || true
        sudo apt-get install --reinstall libtool-bin libtool 2>/dev/null || true

        echo "环境变量设置完成:"
        echo "  JAVA_HOME: $JAVA_HOME"
        echo "  ACLOCAL_PATH: $ACLOCAL_PATH"
        echo "  PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        echo "最终环境检查..."
        echo "PATH: $PATH"
        which java
        which javac
        $JAVA_HOME/bin/java -version || echo "JAVA_HOME/bin/java 不可用"

        # 创建符号链接以确保 buildozer 能找到 Java
        if [ ! -d "/usr/lib/jvm/java-8-openjdk-amd64" ] && [ -d "$JAVA_HOME" ]; then
          echo "创建 Java 符号链接..."
          sudo mkdir -p /usr/lib/jvm
          sudo ln -sf "$JAVA_HOME" /usr/lib/jvm/java-8-openjdk-amd64
          echo "符号链接已创建: /usr/lib/jvm/java-8-openjdk-amd64 -> $JAVA_HOME"
        fi

        echo "开始构建..."
        # 尝试使用更简单的构建方式
        buildozer android debug || {
          echo "构建失败，查看详细日志..."
          if [ -f ".buildozer/android/platform/build-*/build.log" ]; then
            echo "=== 构建日志 ==="
            tail -100 .buildozer/android/platform/build-*/build.log
          fi
          if [ -f ".buildozer/android/platform/python-for-android/dist/*/build.log" ]; then
            echo "=== Python-for-Android 日志 ==="
            tail -100 .buildozer/android/platform/python-for-android/dist/*/build.log
          fi
          exit 1
        }

    - name: 📋 List build output
      if: always()
      run: |
        echo "检查构建输出："
        ls -la
        if [ -d "bin" ]; then
          echo "✅ bin 目录内容："
          ls -la bin/
        else
          echo "❌ bin 目录不存在"
        fi
        if [ -d ".buildozer" ]; then
          echo "📁 .buildozer 目录存在"
          echo "最近的构建日志："
          find .buildozer -name "*.log" -type f -exec tail -50 {} \; 2>/dev/null || echo "没有找到日志文件"
        else
          echo "❌ .buildozer 目录不存在"
        fi

    - name: 📤 Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: pinyin-matcher-apk-${{ github.run_number }}
        path: bin/*.apk
        retention-days: 30

    - name: 🏷️ Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: 拼音匹配器 ${{ github.ref_name }}
        body: |
          ## 📱 拼音匹配器 Android APK

          ### 🆕 新版本特性
          - 自动构建的 Android APK
          - 支持 Android 5.0+ 设备
          - 包含完整的拼音数据库
          - 智能拼音匹配功能
          - 移动端优化界面

          ### 📥 安装说明
          1. 下载下方的 APK 文件
          2. 在 Android 设备上允许安装未知来源应用
          3. 安装 APK 文件
          4. 享受拼音匹配功能

          ### 🔧 技术信息
          - 构建时间: ${{ github.event.head_commit.timestamp }}
          - 提交哈希: ${{ github.sha }}
          - Python 版本: 3.9
          - Kivy 版本: 2.1.0
          - 支持架构: ARM64, ARMv7
          - 最低 Android 版本: 5.0 (API 21)

          ### 📱 应用特点
          - 🔍 智能拼音匹配
          - 📊 完整拼音数据库
          - 🎨 现代化移动端界面
          - 🚀 高性能匹配算法
        files: bin/*.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 💬 Comment on PR
      if: github.event_name == 'pull_request' && success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🎉 APK 构建成功！可以在 [Actions](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) 页面下载构建的 APK 文件。'
          })

    - name: 🧹 Cleanup old artifacts
      if: github.event_name == 'schedule'
      uses: actions/github-script@v7
      with:
        script: |
          // 清理超过30天的构建制品
          const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100
          });

          const thirtyDaysAgo = new Date();
          thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

          for (const artifact of artifacts.artifacts) {
            if (new Date(artifact.created_at) < thirtyDaysAgo) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              console.log(`删除旧制品: ${artifact.name}`);
            }
          }
